<h1 align = center>Numpy Library</h1>

## Creating Numpy Arrays

In [2]:
# to use numpy, we have to import it first. (of course we need to install it first) 
import numpy as np

- Numpy array is created using `array()` method of numpy library. 
- This method requires a python `list` as an argument. We can not only pass required values in the form of list to create a new array can also pass an existed list as an argument and the array() method will convert it into a numpy array. 
- __Syntax__
  - `np.array([a_list_of_elements])`

In [3]:
# creating one dimensional numpy arrays
a_numpy_array = np.array([1,2,3,4,5])

print(a_numpy_array)
print(type(a_numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Creating Multi-Dimensional Numpy Arrays
- The simple array, created from a simple list are called 1 dimensional arrays. But numpy allows us to create arrays from lists of lists. In this case, these array are called multidimensional arrays. 
- If we are to create a numpy array form a list of lists, it will be called a 2 dimensional array. In the case of list of lists of lists, it will be called a 3 dimensional array and so on. 
- The syntax is simple, we just need to pass our list of lists to the array() method 

In [8]:
'''
Creating a 2D Array
'''
list_of_lists = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]

two_d_array = np.array(list_of_lists)

print(two_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
'''
Creating a 3D array
'''
list_of_lists_of_lists = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
]

three_d_array = np.array(list_of_lists_of_lists)

print(three_d_array)
print(type(three_d_array))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>


### Checking the Shape/Dimensions of a Numpy Array
- We can use the `shape` property of a numpy array object to check its dimensions.

In [10]:
print('The shape of our previous created arrays are as follows: ')

shape_one = a_numpy_array.shape
shape_two = two_d_array.shape
shape_three = three_d_array.shape

print(f'The shape of a simple numpy array is : {shape_one}')
print(f'The shape of a 2D numpy array is : {shape_two}')
print(f'The shape of a 3D numpy array is : {shape_three}')

The shape of our previous created arrays are as follows: 
The shape of a simple numpy array is : (5,)
The shape of a 2D numpy array is : (3, 3)
The shape of a 3D numpy array is : (3, 2, 3)


- We can see here, that 1D array has just one row and zero columns, while 2D array is like a matrix having 3 rows and 3 columns. More than 2 dimensional array is called a `tensor` so our 3D array which is actually a tensor, has dimension (3,2,3) which states that there are 2 rows and 2 columns for each matrix and there are total 3 matrix.

## Some Commonly Used Special Numpy Arrays

### Array of Zeros 
- Numpy provides a special method `np.zeros()` to create an array of our desired dimensions filled with zeros. This type of array is useful when we are working on a kind of data in which we need an array having specific dimensions and we will fill it with values as we progress through our program, a neural network is a widely known example. 
- __Syntax__:
  - `np.zeros((a_tuple_stating_dimensions))`
  - Note here, that we are not using `np.array()`, rather a different method `np.zeros()` is being used. 
  - Also note here, that unlike `np.array()` method, we are not passing a list as an argument, rather we are passing a tuple of dimensions. 

In [15]:
tuple_of_dimensions = (3,4) # we want to create an array having 3 rows and 4 columns 

array_of_zeros = np.zeros(tuple_of_dimensions)
print(f'Array with tuple already defined :\n{array_of_zeros}')

array_of_zeros = np.zeros((8,4))
print(f'Array with dimensions directly supplied :\n{array_of_zeros}')



Array with tuple already defined :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array with dimensions directly supplied :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### An Array of Random Numbers 
- Just like array of zeros, we can also create an array filled with random numbers and having our desired dimensions.
- The created array will have random numbers between 0 and 1
- __Syntax__:
  - `np.random.random((a_tuple_of_dimensions))`

In [16]:
random_numbers_array = np.random.random((6,3))
print(random_numbers_array)

[[0.17105327 0.5328783  0.65582809]
 [0.79246413 0.33488983 0.91843924]
 [0.79207365 0.80003912 0.04889634]
 [0.31087318 0.31408865 0.53165674]
 [0.23238708 0.15406339 0.73804291]
 [0.35412497 0.70971702 0.28555703]]


### An Array of Random Numbers With Custom Lower and Upper Range
- Numpy facilitates us in creating arrays filled with numbers with a user defined lower and upper range of these numbers. 
- This kind of array is a one dimensional array. 
- The numbers are not random, but in a continues sequence.
- __Syntax__:
  - `np.arange(lower_bound, upper_bound, step_size(optional))`
  - Note here that the argument is neither a list nor a tuple but a simple comma separated set of arguments mentioning lower and upper bounds. 
  - The lower bound number is included in the result, while the upper bound number is not included. 
- __With Step Size__:
  - We can also pass a step size as a third argument after the lower and upper bounds. The generated numbers will have a gap equal to the mentioned step size.

In [19]:
lower_bound = 1
upper_bound = 21
step_size = 2

# without step size
random_array_with_custom_bounds = np.arange(lower_bound, upper_bound)
print(random_array_with_custom_bounds)

# with step size
with_step_size = np.arange(lower_bound, upper_bound, step_size)
print(with_step_size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]
